version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_address:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_ADDRESS=ON -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_thread:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_THREAD=ON -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_undefined:
    docker:
      - image: qrledger/qrl-docker:bionic
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_UNDEFINED=ON
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  test_python:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: python3 setup.py test

  deploy-pypi:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: python3 setup.py build sdist
      - run: pip install twine
      - run: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - sanitize_address:
          filters:
            tags:
              only: /.*/

      - sanitize_thread:
          filters:
            tags:
              only: /.*/

      - test_python:
          filters:
            tags:
              only: /.*/

      - deploy-pypi:
          requires:
            - build
            - sanitize_address
            - sanitize_thread
            - test_python
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
