version: 2.1
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake .
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_address:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_ADDRESS=ON .
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_thread:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_THREAD=ON .
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  sanitize_undefined:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DSANITIZE_UNDEFINED=ON
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  test_python:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: pip3 install PyScaffold pytest pytest-cov
      - run: pip3 install -e .
      - run: python3 -m pytest --cov=qryptonight tests/

  deploy-pypi:
    docker:
      - image: qrledger/qrl-docker-ci:noble
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: pip3 install PyScaffold
      - run: python3 setup.py build sdist
      - run: pip install twine
      - run: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  build_all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - sanitize_address:
          filters:
            tags:
              only: /.*/

      - sanitize_thread:
          filters:
            tags:
              only: /.*/

      - test_python:
          filters:
            tags:
              only: /.*/

      - deploy-pypi:
          requires:
            - build
            - sanitize_address
            - sanitize_thread
            - test_python
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
