version: 2
jobs:
  build:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: cmake -DBUILD_PYTHON=ON -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5
      - run: make
      - run: export GTEST_COLOR=1 && ctest -VV

  test_python:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: python3 setup.py test

  deploy-pypi:
    docker:
      - image: qrledger/qrl-docker:xenial
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: python3 setup.py build sdist bdist_wheel
      - run: pip install twine
      - run: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - test_python
      - deploy-pypi-check:
          type: approval
          requires:
            - build
            - test_python
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
          branches:
            only: master
      - deploy-pypi:
          requires:
            - deploy-pypi-check
          branches:
            only: master
